"""Permitir valores nulos al registrar 2.O

Revision ID: 948826ec0fea
Revises: c0f604e8a062
Create Date: 2024-10-22 11:03:27.961043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '948826ec0fea'
down_revision = 'c0f604e8a062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classusuarios', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('estatura',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('actividad',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('metabolismobasal',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('imc',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('requerimentoagua',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('requerimientocalorico',
               existing_type=mysql.INTEGER(display_width=6),
               nullable=True)
        batch_op.alter_column('objetivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cantidad_comidas',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_unique_constraint(None, ['usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classusuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('cantidad_comidas',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('objetivo',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('requerimientocalorico',
               existing_type=mysql.INTEGER(display_width=6),
               nullable=False)
        batch_op.alter_column('requerimentoagua',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('imc',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('metabolismobasal',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('actividad',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('edad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('estatura',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('peso',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
